age = (int("18"))
first_name = (str("Joe"))
last_name = (str("Mom"))
gender = (str("Male"))
height = (float("1.98"))
nationality= (str("Brazilian"))
print("age: ", str(age), "\nname: ", first_name, last_name, "\nGender: ", gender, "\nheight :", height,  "\nnationality: ", nationality)
